#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!

echo "Launching Gazebo..."
sleep 5s
roslaunch pioneer_gazebo pioneer_traffic_utm_auro_world.launch &
pid="$pid $!"

echo "Loading initialisation parameters..."
sleep 5s
roslaunch pioneer_description utm_auro_traffic_description.launch

echo "Launching Pioneers in Gazebo stack..."
sleep 5s
for i in `seq 1 2`;
do
  roslaunch pioneer_description generic_pioneer.launch name:=pioneer$i pose:="-x $(rosparam get /pioneer$i/x) -y $(rosparam get /pioneer$i/y) -Y $(rosparam get /pioneer$i/a)" &
  pid="$pid $!"
  sleep 2s
done

echo "Launching map server..."
sleep 5s
roslaunch nav_bundle map_server.launch map_name:=utm_auro &
pid="$pid $!"

echo "Launching navigation stack..."
rosparam load $(rospack find utm_traffic)/launch/utm_agent_auro_params.yaml &
sleep 5s
for i in `seq 1 2`;
do
  roslaunch nav_bundle single_navigation_utm_auro_traffic.launch robot_name:=pioneer$i x:="$(rosparam get /pioneer$i/x)" y:="$(rosparam get /pioneer$i/y)" yaw:="$(rosparam get /pioneer$i/a)" pioneer_traffic:="pioneer_traffic_sim_auro" waypoint_file:="waypoints_auro"&
  pid="$pid $!"
  sleep 2s
done

echo "Initializing UTM graph manager..."
sleep 5s
rosrun utm_agents utm_manager &
pid="$pid $!"

echo "Launching agents..."
rosparam load $(rospack find utm_agents)/launch/utm_auro_agents_params.yaml &
sleep 5s
for i in `seq 0 37`;
do
  roslaunch utm_agents utm_agent.launch agentID:=$i num_traffic:=1&
  pid="$pid $!"
  sleep 2s
done
echo "Initializing graph..."
sleep 5s
rosrun utm_traffic utm_graph_publisher &

echo "Launching rviz..."
sleep 5s
roslaunch pioneer_description multi_pioneer_rviz.launch rviz_config:=utm_auro_multi_pioneer&
pid="$pid $!"

#echo "Sending initial waypoints..."
#sleep 5s
#rostopic pub -1 /pioneer1/cmd_map_goal geometry_msgs/Twist '[17.0, -17.0, 0.0]' '[0.0, 0.0, 0.0]' &
#rostopic pub -1 /pioneer2/cmd_map_goal geometry_msgs/Twist '[3.0, -3.0, 0.0]' '[0.0, 0.0, 0.0]' &
#rostopic pub -1 /pioneer3/cmd_map_goal geometry_msgs/Twist '[17.0, -20.0, 0.0]' '[0.0, 0.0, 0.0]' &
#rostopic pub -1 /pioneer4/cmd_map_goal geometry_msgs/Twist '[3.0, 0.0, 0.0]' '[0.0, 0.0, 0.0]' &
#rostopic pub -1 /pioneer1/cmd_map_goal geometry_msgs/Twist '[1.86, -0.26, 0.0]' '[0.0, 0.0, 0.0]' &
#rostopic pub -1 /pioneer2/cmd_map_goal geometry_msgs/Twist '[-0.42, -0.26, 0.0]' '[0.0, 0.0, 0.0]' &
#rostopic pub -1 /pioneer3/cmd_map_goal geometry_msgs/Twist '[1.86, 3.24, 0.0]' '[0.0, 0.0, 0.0]' &
#rostopic pub -1 /pioneer4/cmd_map_goal geometry_msgs/Twist '[-0.42, 3.24, 0.0]' '[0.0, 0.0, 0.0]' &

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

echo "Simulation active"

sleep 24h
